#!/bin/bash
## bash <(curl -Ls https://raw.githubusercontent.com/jenaze/Ubunto/master/count_ip.sh)
 
REQUIRED_PKG="sqlite3"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
#echo Checking for $REQUIRED_PKG: $PKG_OK
if [ "" = "$PKG_OK" ]; then
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  sudo apt-get --yes install $REQUIRED_PKG
fi

sudo sqlite3 -line /etc/x-ui/x-ui.db "SELECT 
*,
LENGTH(ips) - LENGTH(REPLACE(ips, ',', '')) + 1 as ip_count
FROM
inbound_client_ips
WHERE 
LENGTH(ips) - LENGTH(REPLACE(ips, ',', '')) + 1 > 2"
